# Generated by Django 5.2.7 on 2025-10-21 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('grado', models.CharField(max_length=20)),
                ('tema', models.CharField(max_length=50)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('opcion_a', models.CharField(max_length=200)),
                ('opcion_b', models.CharField(max_length=200)),
                ('opcion_c', models.CharField(max_length=200)),
                ('opcion_d', models.CharField(max_length=200)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ejercicios.leccion')),
            ],
        ),
    ]
